### ISSUE TITLE
Cannot create jar

### ISSUE THREAD

**Issue by alwatto** [neo-technology/neo4j-example-auth-plugins#15]
[INFO] Running org.neo4j.example.auth.plugin.MyAuthPluginTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.071 s <<< FAILURE! - in org.neo4j.example.auth.plugin.MyAuthPluginTest
[ERROR] shouldLogErrorOnNonExistingConfigFile  Time elapsed: 0.066 s  <<< ERROR!

this is the error i am getting when following the steps

**Comment by mnd999** [comment]
Closing this old issue, the jar creation seems to work in our CI. If it's still a problem for you please feel free to reopen
