### ISSUE TITLE
AuthPlugin is not working

### ISSUE THREAD

**Issue by jakinto** [neo-technology/neo4j-example-auth-plugins#3]
I can't make the **MyAuthPlugin** work. I'm using a **neo4j-community-3.1.2**,  this is my **neo4j.conf**:

```
dbms.security.auth_enabled=true
dbms.security.auth_provider=plugin-org.test.neo4j.plugin.MyAuthPlugin
dbms.security.plugin.authentication_enabled=true
dbms.security.plugin.authorization_enabled=true
```
And **MyAuthPlugin** is  extending AuthPlugin.Adapter. 

No errors when starting Neo4j. Any suggestions?

Thank you.

**Comment by jexp** [comment]
You don't need it anymore.  Neo4j has auth built in since 2.3

**Comment by jakinto** [comment]
I want to implement my own authentication/authorization for a  **neo4j-community-3.1.2**. How can I do that?, is there any example available?

Thanks in advance.

**Comment by jakinto** [comment]
Is this deprecated?

https://neo4j.com/docs/developer-manual/current/extending-neo4j/auth-plugins/

**Comment by jexp** [comment]
it's not used anymore at least, we should probably remove it.

**Comment by jakinto** [comment]
So, we don't have the possibility to implement a custom authorization, even in the enterprise version?

**Comment by fickludd** [comment]
Hi jakinto,

I think there is some confusion here. The AuthPlugin API is not deprecated. The reason the MyAuthPlugin example is not working for you is that all security features apart from basic user management are enterprise only. Therefore **neo4j-community-3.1.2** is not responding, while neo4j-enterprise-3.1.2 certainly would.

Best,
Johan

**Comment by jakinto** [comment]
Hi!

I tried to deploy a plugin that contains a class implementing **org.neo4j.server.security.enterprise.auth.plugin.spi.AuthPlugin** in a **neo4j-enterprise-3.1.4** and I'm getting:

> 2017-05-11 06:17:15.664+0000 ERROR Failed to load security module.
> 2017-05-11 06:17:15.668+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@74846614' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@74846614' was successfully initialized, but failed to start. Please see attached cause exception.
> org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@74846614' was successfully initialized, but failed to start. Please see attached cause exception.
>         at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
>         at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:230)
>         at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
>         at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:68)
>         at org.neo4j.server.enterprise.EnterpriseEntryPoint.main(EnterpriseEntryPoint.java:32)
> Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@74846614' was successfully initialized, but failed to start. Please see attached cause exception.
>         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
>         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
>         at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:202)
>         ... 3 more
> Caused by: java.lang.RuntimeException: Failed to load security module.
>         at org.neo4j.kernel.impl.factory.EditionModule.setupSecurityModule(EditionModule.java:185)
>         at org.neo4j.kernel.impl.enterprise.EnterpriseEditionModule.setupEnterpriseSecurityModule(EnterpriseEditionModule.java:97)
>         at org.neo4j.kernel.impl.enterprise.EnterpriseEditionModule.setupSecurityModule(EnterpriseEditionModule.java:90)
>         at org.neo4j.kernel.impl.factory.DataSourceModule.<init>(DataSourceModule.java:180)
>         at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.createDataSource(GraphDatabaseFacadeFactory.java:243)
>         at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:151)
>         at org.neo4j.graphdb.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:36)
>         at org.neo4j.server.enterprise.EnterpriseNeoServer.lambda$static$1(EnterpriseNeoServer.java:91)
>         at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
>         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
>         ... 5 more
> Caused by: java.lang.IllegalArgumentException: Illegal configuration: Failed to load auth plugin 'plugin-MyAuthPlugin'.
>         at org.neo4j.server.security.enterprise.auth.EnterpriseSecurityModule.illegalConfiguration(EnterpriseSecurityModule.java:316)
>         at org.neo4j.server.security.enterprise.auth.EnterpriseSecurityModule.createPluginRealms(EnterpriseSecurityModule.java:264)
>         at org.neo4j.server.security.enterprise.auth.EnterpriseSecurityModule.newAuthManager(EnterpriseSecurityModule.java:151)
>         at org.neo4j.server.security.enterprise.auth.EnterpriseSecurityModule.setup(EnterpriseSecurityModule.java:94)
>         at org.neo4j.kernel.impl.factory.EditionModule.setupSecurityModule(EditionModule.java:135)
>         ... 14 more

Any ideas?

**Comment by jakinto** [comment]
The exception is so generic that it gives me no leads. Any help?

**Comment by fickludd** [comment]
Oh, that is not expected. We are looking into this issue, and will come back soon!

**Comment by jakinto** [comment]
Thank you very much.

**Comment by OliviaYtterbrink** [comment]
Your config settings aren't quite correct, it should read: 

```
dbms.security.auth_provider=plugin-org.neo4j.example.auth.plugin.MyAuthPlugin
```

The error message you got was saying that there was no auth provider plugin with the name specified.

**Comment by jakinto** [comment]
Same error changing auth_provider:

Failed to load auth plugin 'plugin-org.neo4j.example.auth.plugin.MyAuthPlugin'

**Comment by vinnusaurus** [comment]
@jakinto hey can you tell me how to debug the example project [](https://github.com/neo4j/neo4j-example-auth-plugins), I am newbie to java
