### ISSUE TITLE
 api.log().info(...) not working

### ISSUE THREAD

**Issue by jakinto** [neo-technology/neo4j-example-auth-plugins#4]
AuthProviderOperationsap.log().info("....") is not working inside AuthPlugin. 

Is there any property to enable this?

**Comment by OliviaYtterbrink** [comment]
I would need a bit more information to help you, what is it about the log that doesn't work?

**Comment by jakinto** [comment]
It's not logging in neo4j.log

**Comment by OliviaYtterbrink** [comment]
The log that you get from AuthProviderOperations is logging to security.log

**Comment by jakinto** [comment]
Perfect, sorry for the inconvenience.
