### ISSUE TITLE
[Story] OpenID Connect OpenIDC OidC Oauth2 JWT

### ISSUE THREAD

**Issue by styk-tv** [neo-technology/neo4j-example-auth-plugins#6]
I'm not too much of a Java coder but I'd like to use official GraphQL plugin with OpenID Connect token, In two lines of config you could specify endpoint for oidc server and client name. Settings are then auto-discovered using .well-known endpoint of a provider (like Keycloak or Auth0) Users are authorized at provider and token is posted with Authorization header following  Bearer prefix. Tokens could contain roles or perhaps even further groups. Groups could protect GraphQL resolvers. If user doesn't have a group listed in a token, it wouild be refused execution. Further authorized user's details contained in the token could be used as part of the query and maybe even extension of IDL definitions themselves. Simple decorator could be used to described what groups could perform queries, subscriptions, mutations. No complex authentication mechanism needs to exist in the plugin, just a simple hostname and client. Everything else comes with the token. As a bonus easy token verification can be performed (signature match - make sure its issued by the same provider, expiration match - make sure token is not expired) That's really it. Externalized parameters could be specified from main settings file so its easy to play with on the Neo4j Desktop

I know everyone is supposed to deal with Auth on their own, GraphQL has policy Do Not Get Involved with Auth. Neo4j has a nice plugin repo (this repo) with 3 examples. Maybe this is a case for Auth0 people that seem to like to stick examples of usage of OIDC wherever they can (many thanks for 100's of examples on the net so far). I guess next one is due right here.. would be nice. Can anyone help? 

Only option i have left is to reimplement GraphQL plugin outside of Neo4j with py2neo, graphene and maybe flask-graphql, jwt lib and maybe idlewild for idl schema support which I got used to. However from a public endpoint security perspective what chance do I have to do it right? 

Maybe use client on api and query graphql endpoint and then re-post to mobile client? But then i need to build an implementation compatible with Relay which I would like to take advantage of. Don't really want to use simple rest since graphql is an option.  Do you know what i mean?

**Comment by mnd999** [comment]
Neo4j has had official support for OpenID Connect since version 4.4, so I will close this for now. Please feel free to reopen if this is still and issue for you.
